### ISSUE TITLE
resistance coin has a virus it crashed my computer and i had to hard reinstall windows 10 \

### ISSUE THREAD

**Issue by Cook1eBoyz** [ResistancePlatform/resistance-platform-release#9]
resistance coin has a virus it crashed my computer and i had to hard reinstall windows 10

**Comment by solardiz** [comment]
What makes you think there's a virus here? We're aware of detection of the Resistance installer for Windows by some AV tools because of the bundled miner - this is issue #7 here. However, this is not an actual virus - it is a miner - and the AV tools that do detect this miner do not call it a virus, e.g. https://www.virustotal.com/gui/file/67f35827f22980580f07ba17918f868c52e69b97ceed41142e127e49c3758735/detection currently shows detection by 9 out of 66 AV tools, and none of those 9 descriptions say this is a virus - e.g., Kaspersky and ZoneAlarm report "Not-a-virus:HEUR:RiskTool.Win32.BitCoinMiner.gen" and Avast reports "Win32:Miner-BA [Trj]". While well-intentioned by the makers of those AV tools, this does indeed confuse people and causes inconvenience in installing Resistance, so we're looking into ways to minimize such AV detection.

We're sorry your computer crashed and you ended up reinstalling Windows. However, we really see no relation to our software here.

We'd appreciate more detail from you on the "virus" claim and how you think these events are related. Thanks.

(Personally, I am working on the core & miner source code, and not on these Windows builds of them. However, I felt your report needed a response within a day, so I provided one above instead of waiting for a more directly involved team member to do so.)

**Comment by lukewegryn** [comment]
We've responded to it to the fullest extent possible in absence of further communication from the reporter. Closing.
